### ISSUE TITLE
Save options wait:true and patch:true are mutually exclusive

### ISSUE THREAD

**Issue by bryanspears** [AmpersandJS/ampersand-model#53] opened 2015-06-26 00:29 UTC
If this is intentional, then close my issue, otherwise this needs a look.

https://github.com/AmpersandJS/ampersand-model/blob/master/ampersand-model.js#L64
and
https://github.com/AmpersandJS/ampersand-model/blob/master/ampersand-model.js#L67

Line 67 overrides what was done on 64 if both wait and patch are true.

**Comment by pgilad** [comment] 2015-06-26 06:29
It doesn't override, it just adds more properties to `options.attrs` that will be found in `model.serialize()`.

I'm not sure if this is a mistake or not. If you can put together a test case for this it would be awesome.

**Comment by bryanspears** [comment] 2015-06-26 06:37
Certainly, it's not a direct override, but lets say I have a model with a, b, and c in it. b gets changed, mode is patch/wait true, which means at line 64, options.attrs = {b}, bu after 67 it's {a, b, c}

Effectively overriding the object, but not the affected keys. Entirely obliterates the PATCH call.

I should have a chance to write up a test tomorrow unless someone beats me to it.

**Comment by bryanspears** [comment] 2015-06-26 06:42
Excuse me. I shouldn't post when tired. We effectively said the same thing. :smile:

**Comment by pgilad** [comment] 2015-06-26 06:49
This is actually a duplicate of https://github.com/AmpersandJS/ampersand-model/issues/13

**Closed** 2015-08-26 21:49 UTC
